node {
   // Mark the code checkout 'stage'....
   stage 'Checkout'

   // Checkout code from repository
   checkout scm
}

node {
	stage 'Build Solution'
	bat 'powershell.exe -ExecutionPolicy RemoteSigned -File "%WORKSPACE%/Deploy/BuildSolution.ps1"'
}

node {
    stage 'Unit Tests'
    bat 'powershell.exe -ExecutionPolicy RemoteSigned -File "%WORKSPACE%/Deploy/DeployDacpac.ps1"  -dacpac "%WORKSPACE%/Test/Database.UnitTests/bin/Debug/Database.UnitTests.dacpac" -publishProfile "%WORKSPACE%/Test/Database.UnitTests/Database.UnitTests.publishProfile.xml" -databaseName Database.UnitTests'

    bat 'powershell.exe -ExecutionPolicy RemoteSigned -File "%WORKSPACE%/Deploy/RunUnitTests.ps1"  -projectPath "%WORKSPACE%/"'
    
}