node {
   // Mark the code checkout 'stage'....
   stage 'Checkout'

   // Checkout code from repository
   checkout scm
}

node {
	stage 'Build Solution'
	bat '"%WORKSPACE%/Deploy/BuildSolution.ps1"'
}
